version: "3.9"
services:

  node:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    container_name: node-application
    ports:
      - "9000:3000"
    restart: always

  nginx:
    build: .docker/nginx
    ports:
      - '80:80'
    depends_on:
      - node
